Repository mujik-tigers/you-together, pull requests merged in 2024-04, with the labels that each got.

#13 merge to dev
  src/docs/asciidoc/api/room.adoc
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/dto/RoomDetail.java
  src/main/java/site/youtogether/room/dto/RoomList.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/util/api/ResponseResult.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
Labels: test

#14 merge for API documentation deployment
  src/docs/asciidoc/api/room.adoc
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/dto/RoomDetail.java
  src/main/java/site/youtogether/room/dto/RoomList.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/util/api/ResponseResult.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
Labels: release

#16 fix: API 응답 명세서 수정
  src/main/java/site/youtogether/room/dto/RoomList.java
  src/main/java/site/youtogether/room/dto/RoomListDetail.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/test/java/site/youtogether/RestDocsSupport.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
Labels: release

#17 feat: 방 목록 조회 기능 구현 완료
  .github/workflows/auto-deploy.yml
  .github/workflows/test-report.yml
  .gitignore
  build.gradle
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/config/WebConfig.java
  src/main/java/site/youtogether/resolver/Address.java
  src/main/java/site/youtogether/resolver/AddressArgumentResolver.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/dto/RoomList.java
  src/main/java/site/youtogether/room/dto/RoomListDetail.java
  src/main/java/site/youtogether/room/infrastructure/RoomSearchStreamBuilder.java
  src/main/java/site/youtogether/room/infrastructure/RoomStorage.java
  src/main/java/site/youtogether/room/infrastructure/RoomStorageCustom.java
  src/main/java/site/youtogether/room/infrastructure/RoomStorageCustomImpl.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/infrastructure/UserStorage.java
  src/main/java/site/youtogether/util/Initializer.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
Labels: test, new feature

#18 merge
  .github/workflows/auto-deploy.yml
  .github/workflows/test-report.yml
  .gitignore
  build.gradle
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/config/WebConfig.java
  src/main/java/site/youtogether/resolver/Address.java
  src/main/java/site/youtogether/resolver/AddressArgumentResolver.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/dto/RoomList.java
  src/main/java/site/youtogether/room/dto/RoomListDetail.java
  src/main/java/site/youtogether/room/infrastructure/RoomSearchStreamBuilder.java
  src/main/java/site/youtogether/room/infrastructure/RoomStorage.java
  src/main/java/site/youtogether/room/infrastructure/RoomStorageCustom.java
  src/main/java/site/youtogether/room/infrastructure/RoomStorageCustomImpl.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/infrastructure/UserStorage.java
  src/main/java/site/youtogether/util/Initializer.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
Labels: release

#20 refactor: 방 생성 / 방 입장 관련 구조 변경 및 개선 완료
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/config/WebConfig.java
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/GlobalExceptionHandler.java
  src/main/java/site/youtogether/exception/cookie/CookieInvalidException.java
  src/main/java/site/youtogether/exception/cookie/CookieNoExistenceException.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/user/infrastructure/UserStorage.java
  src/main/java/site/youtogether/user/infrastructure/UserTrackingStorage.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/main/java/site/youtogether/util/Initializer.java
  src/main/java/site/youtogether/util/RandomUtil.java
  src/main/java/site/youtogether/util/interceptor/SingleRoomCheckInterceptor.java
  src/main/java/site/youtogether/util/resolver/UserTracking.java
  src/main/java/site/youtogether/util/resolver/UserTrackingArgumentResolver.java
  src/test/java/site/youtogether/RestDocsSupport.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/infrastructure/UserTrackingStorageTest.java
Labels: refactor, new feature

#21 release
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/config/WebConfig.java
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/GlobalExceptionHandler.java
  src/main/java/site/youtogether/exception/cookie/CookieInvalidException.java
  src/main/java/site/youtogether/exception/cookie/CookieNoExistenceException.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/user/infrastructure/UserStorage.java
  src/main/java/site/youtogether/user/infrastructure/UserTrackingStorage.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/main/java/site/youtogether/util/Initializer.java
  src/main/java/site/youtogether/util/RandomUtil.java
  src/main/java/site/youtogether/util/interceptor/SingleRoomCheckInterceptor.java
  src/main/java/site/youtogether/util/resolver/UserTracking.java
  src/main/java/site/youtogether/util/resolver/UserTrackingArgumentResolver.java
  src/test/java/site/youtogether/RestDocsSupport.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/infrastructure/UserTrackingStorageTest.java
Labels: release

#30 feat: 방 입장 기능 구현
  src/docs/asciidoc/api/room.adoc
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/room/RoomNoExistenceException.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/dto/RoomDetail.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/util/api/ResponseResult.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
Labels: new feature

#31 Feat: 웹 소켓 환경 구축
  build.gradle
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/config/WebSocketConfig.java
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/user/UserNoExistenceException.java
  src/main/java/site/youtogether/message/ChatMessage.java
  src/main/java/site/youtogether/message/MessageType.java
  src/main/java/site/youtogether/message/application/RedisPublisher.java
  src/main/java/site/youtogether/message/application/RedisSubscriber.java
  src/main/java/site/youtogether/message/presentation/MessageController.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/dto/RoomDetail.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/main/java/site/youtogether/util/Initializer.java
  src/main/java/site/youtogether/util/interceptor/StompHandshakeInterceptor.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
Labels: new feature

#32 Feat: 채팅 전반적인 기능 구현
  src/docs/asciidoc/api/user.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/message/ParticipantsInfoMessage.java
  src/main/java/site/youtogether/message/application/RedisPublisher.java
  src/main/java/site/youtogether/message/application/RedisSubscriber.java
  src/main/java/site/youtogether/message/presentation/MessageController.java
  src/main/java/site/youtogether/message/presentation/MessageEventListener.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/user/dto/UpdateUserForm.java
  src/main/java/site/youtogether/user/dto/UserInfo.java
  src/main/java/site/youtogether/user/infrastructure/UserTrackingStorage.java
  src/main/java/site/youtogether/user/presentation/UserController.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/main/java/site/youtogether/util/Initializer.java
  src/main/java/site/youtogether/util/api/ResponseResult.java
  src/test/java/site/youtogether/RestDocsSupport.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/application/UserServiceTest.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
Labels: new feature

#36 refactor: userStorage 제거
  src/main/java/site/youtogether/message/presentation/MessageController.java
  src/main/java/site/youtogether/message/presentation/MessageEventListener.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/user/infrastructure/UserStorage.java
  src/main/java/site/youtogether/util/Initializer.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/user/application/UserServiceTest.java
Labels: refactor

#37 release: userStorage 제거
  src/main/java/site/youtogether/message/presentation/MessageController.java
  src/main/java/site/youtogether/message/presentation/MessageEventListener.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/user/infrastructure/UserStorage.java
  src/main/java/site/youtogether/util/Initializer.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/user/application/UserServiceTest.java
Labels: release

#39 Feat: 방 입장 시 검증 기능 구현
  src/docs/asciidoc/api/room.adoc
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/GlobalExceptionHandler.java
  src/main/java/site/youtogether/exception/room/PasswordNotMatchException.java
  src/main/java/site/youtogether/exception/room/RoomCapacityExceededException.java
  src/main/java/site/youtogether/message/presentation/MessageEventListener.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/dto/PasswordInput.java
  src/main/java/site/youtogether/room/dto/RoomSettings.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/infrastructure/UserTrackingStorage.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/main/java/site/youtogether/util/interceptor/StompHandshakeInterceptor.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/application/UserServiceTest.java
Labels: new feature

#40 release: 방 입장 시 검증 기능 배포
  src/docs/asciidoc/api/room.adoc
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/GlobalExceptionHandler.java
  src/main/java/site/youtogether/exception/room/PasswordNotMatchException.java
  src/main/java/site/youtogether/exception/room/RoomCapacityExceededException.java
  src/main/java/site/youtogether/message/presentation/MessageEventListener.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/dto/PasswordInput.java
  src/main/java/site/youtogether/room/dto/RoomSettings.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/infrastructure/UserTrackingStorage.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/main/java/site/youtogether/util/interceptor/StompHandshakeInterceptor.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/application/UserServiceTest.java
Labels: release

#43 modify: 방 생성 및 입장 시 유저 객체를 반환하도록 API 응답 변경
  src/main/java/site/youtogether/room/dto/RoomDetail.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
Labels: refactor

#48 Feat: 다른 참가자들의 역할 변경 기능 구현
  src/docs/asciidoc/api/user.adoc
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/user/HigherOrEqualRoleChangeException.java
  src/main/java/site/youtogether/exception/user/HigherOrEqualRoleUserChangeException.java
  src/main/java/site/youtogether/exception/user/NotManageableUserException.java
  src/main/java/site/youtogether/exception/user/SelfRoleChangeException.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/dto/RoomDetail.java
  src/main/java/site/youtogether/user/Role.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/user/dto/UpdateUserForm.java
  src/main/java/site/youtogether/user/dto/UserRoleChangeForm.java
  src/main/java/site/youtogether/user/presentation/UserController.java
  src/main/java/site/youtogether/util/api/ResponseResult.java
  src/test/java/site/youtogether/room/RoomTest.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/application/UserServiceTest.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
Labels: new feature

#49 release: 다른 사람의 역할 변경 기능 배포
  src/docs/asciidoc/api/user.adoc
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/user/HigherOrEqualRoleChangeException.java
  src/main/java/site/youtogether/exception/user/HigherOrEqualRoleUserChangeException.java
  src/main/java/site/youtogether/exception/user/NotManageableUserException.java
  src/main/java/site/youtogether/exception/user/SelfRoleChangeException.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/dto/RoomDetail.java
  src/main/java/site/youtogether/user/Role.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/user/dto/UpdateUserForm.java
  src/main/java/site/youtogether/user/dto/UserRoleChangeForm.java
  src/main/java/site/youtogether/user/presentation/UserController.java
  src/main/java/site/youtogether/util/api/ResponseResult.java
  src/test/java/site/youtogether/room/RoomTest.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/application/UserServiceTest.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
Labels: release

#50 docs: 매니저보다 낮은 등급의 유저는 다른 유저의 역할을 변경할 수 없도록 검증한 기능 문서화
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
Labels: documentation

#51 release docs
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
Labels: documentation

#53 feat: VIEWER 는 채팅 메시지를 보낼 수 없도록 기능 구현
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/user/ChatMessageSendDeniedException.java
  src/main/java/site/youtogether/message/presentation/MessageController.java
  src/main/java/site/youtogether/user/User.java
Labels: new feature

#54 release: 채팅을 못 치도록 막는 기능 배포
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/user/ChatMessageSendDeniedException.java
  src/main/java/site/youtogether/message/presentation/MessageController.java
  src/main/java/site/youtogether/user/User.java
Labels: release

#57 release: 제목 변경 기능 구현 배포
  src/docs/asciidoc/api/room.adoc
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/user/ChangeRoomTitleDeniedException.java
  src/main/java/site/youtogether/message/RoomTitleMessage.java
  src/main/java/site/youtogether/message/application/RedisSubscriber.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/dto/RoomTitleChangeForm.java
  src/main/java/site/youtogether/room/dto/UpdatedRoomTitle.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/presentation/UserController.java
  src/main/java/site/youtogether/util/api/ResponseResult.java
  src/test/java/site/youtogether/room/RoomTest.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
Labels: release

#61 refactor: redis pub/sub 구조 없애고, stomp 만 사용하기
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/message/application/MessageService.java
  src/main/java/site/youtogether/message/application/RedisPublisher.java
  src/main/java/site/youtogether/message/presentation/MessageController.java
  src/main/java/site/youtogether/message/presentation/MessageEventListener.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/user/application/UserService.java
Labels: refactor

#62 release: redis pub/sub 구조 없애고, stomp 만 사용하기
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/message/application/MessageService.java
  src/main/java/site/youtogether/message/application/RedisPublisher.java
  src/main/java/site/youtogether/message/presentation/MessageController.java
  src/main/java/site/youtogether/message/presentation/MessageEventListener.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/user/application/UserService.java
Labels: release

#64 refactor: 도메인 역할 변경
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/user/User.java
Labels: refactor

#65 feat: 호스트가 방을 나갈 경우 방장 위임 기능 구현
  src/main/java/site/youtogether/exception/room/RoomEmptyException.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/user/Role.java
  src/main/java/site/youtogether/user/User.java
  src/test/java/site/youtogether/room/RoomTest.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
Labels: new feature

#66 release: 방장이 방을 나가는 경우의 기능 배포
  src/main/java/site/youtogether/exception/room/RoomEmptyException.java
  src/main/java/site/youtogether/message/presentation/MessageEventListener.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/user/Role.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/user/infrastructure/UserTrackingStorage.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/main/java/site/youtogether/util/Initializer.java
  src/main/java/site/youtogether/util/interceptor/StompHandshakeInterceptor.java
  src/test/java/site/youtogether/room/RoomTest.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
Labels: release

#68 refactor: Cookie → JWT
  build.gradle
  src/main/java/site/youtogether/config/PropertiesConfig.java
  src/main/java/site/youtogether/config/property/JwtProperties.java
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/GlobalExceptionHandler.java
  src/main/java/site/youtogether/exception/cookie/CookieInvalidException.java
  src/main/java/site/youtogether/exception/cookie/CookieNoExistenceException.java
  src/main/java/site/youtogether/exception/jwt/AuthorizationHeaderNoExistenceException.java
  src/main/java/site/youtogether/exception/jwt/InvalidTokenException.java
  src/main/java/site/youtogether/jwt/JwtService.java
  src/main/java/site/youtogether/message/ChatMessage.java
  src/main/java/site/youtogether/message/presentation/MessageEventListener.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/infrastructure/UserTrackingStorage.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/main/java/site/youtogether/util/Initializer.java
  src/main/java/site/youtogether/util/interceptor/SingleRoomCheckInterceptor.java
  src/main/java/site/youtogether/util/interceptor/StompHandshakeInterceptor.java
  src/main/java/site/youtogether/util/resolver/UserTrackingArgumentResolver.java
  src/test/java/site/youtogether/RestDocsSupport.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/infrastructure/UserTrackingStorageTest.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
Labels: refactor, new feature

#69 release: 쿠키 -> 토큰 리팩토링
  build.gradle
  src/main/java/site/youtogether/config/PropertiesConfig.java
  src/main/java/site/youtogether/config/property/JwtProperties.java
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/GlobalExceptionHandler.java
  src/main/java/site/youtogether/exception/cookie/CookieInvalidException.java
  src/main/java/site/youtogether/exception/cookie/CookieNoExistenceException.java
  src/main/java/site/youtogether/exception/jwt/AuthorizationHeaderNoExistenceException.java
  src/main/java/site/youtogether/exception/jwt/InvalidTokenException.java
  src/main/java/site/youtogether/jwt/JwtService.java
  src/main/java/site/youtogether/message/ChatMessage.java
  src/main/java/site/youtogether/message/presentation/MessageEventListener.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/infrastructure/UserTrackingStorage.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/main/java/site/youtogether/util/Initializer.java
  src/main/java/site/youtogether/util/interceptor/SingleRoomCheckInterceptor.java
  src/main/java/site/youtogether/util/interceptor/StompHandshakeInterceptor.java
  src/main/java/site/youtogether/util/resolver/UserTrackingArgumentResolver.java
  src/test/java/site/youtogether/RestDocsSupport.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/infrastructure/UserTrackingStorageTest.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
Labels: release
