Repository mujik-tigers/you-together, pull requests merged in 2024-05, with the labels that each got.

#74 feat: 비디오 싱크 맞추기 기능 구현
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/playlist/InvalidVideoRateException.java
  src/main/java/site/youtogether/exception/playlist/PlayingVideoNoExistenceException.java
  src/main/java/site/youtogether/message/VideoSyncInfoMessage.java
  src/main/java/site/youtogether/message/presentation/MessageController.java
  src/main/java/site/youtogether/playlist/PlayerState.java
  src/main/java/site/youtogether/playlist/PlayingVideo.java
  src/main/java/site/youtogether/playlist/application/PlayingVideoService.java
  src/main/java/site/youtogether/playlist/application/PlaylistService.java
  src/main/java/site/youtogether/playlist/infrastructure/PlayingVideoStorage.java
  src/main/java/site/youtogether/playlist/presentation/PlaylistController.java
  src/main/java/site/youtogether/room/Room.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/util/api/ResponseResult.java
Labels: new feature

#75 refactor: null 예외 확인 추가 및 구조 개선
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/test/java/site/youtogether/room/RoomTest.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/UserTest.java
  src/test/java/site/youtogether/user/application/UserServiceTest.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
Labels: refactor, test

#77 Test: Playlist 테스트 코드 작성
  src/docs/asciidoc/api/playlist.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/youtogether/playlist/Video.java
  src/test/java/site/youtogether/RestDocsSupport.java
  src/test/java/site/youtogether/playlist/PlaylistTest.java
  src/test/java/site/youtogether/playlist/application/PlaylistServiceTest.java
  src/test/java/site/youtogether/playlist/presentation/PlaylistControllerTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
Labels: documentation, test

#78 Release: Playlist 기능 배포
  src/docs/asciidoc/api/playlist.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/playlist/Playlist.java
  src/main/java/site/youtogether/playlist/Video.java
  src/main/java/site/youtogether/playlist/application/PlaylistService.java
  src/main/java/site/youtogether/playlist/infrastructure/PlayingVideoStorage.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/test/java/site/youtogether/RestDocsSupport.java
  src/test/java/site/youtogether/playlist/PlaylistTest.java
  src/test/java/site/youtogether/playlist/application/PlaylistServiceTest.java
  src/test/java/site/youtogether/playlist/presentation/PlaylistControllerTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
Labels: release

#80 feat: 동시성 처리
  build.gradle
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/playlist/InvalidVideoNumberException.java
  src/main/java/site/youtogether/exception/playlist/PlaylistLockAcquisitionFailureException.java
  src/main/java/site/youtogether/playlist/Playlist.java
  src/main/java/site/youtogether/playlist/Video.java
  src/main/java/site/youtogether/playlist/application/PlaylistService.java
  src/main/java/site/youtogether/playlist/dto/NextVideo.java
  src/main/java/site/youtogether/playlist/dto/VideoInfo.java
  src/main/java/site/youtogether/playlist/presentation/PlaylistController.java
  src/main/java/site/youtogether/room/Participant.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/util/RandomUtil.java
  src/main/java/site/youtogether/util/aop/ConcurrencyHandlingAspect.java
  src/main/java/site/youtogether/util/aop/PlaylistSynchronize.java
  src/main/java/site/youtogether/util/aop/RoomSynchronize.java
  src/main/java/site/youtogether/util/aop/UserSynchronize.java
  src/test/java/site/youtogether/playlist/PlaylistTest.java
  src/test/java/site/youtogether/playlist/application/PlaylistServiceTest.java
  src/test/java/site/youtogether/playlist/presentation/PlaylistControllerTest.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
  src/test/java/site/youtogether/util/aop/ConcurrencyHandlingAspectTest.java
Labels: test, new feature

#81 release: 동시성 처리
  build.gradle
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/playlist/InvalidVideoNumberException.java
  src/main/java/site/youtogether/exception/playlist/PlaylistLockAcquisitionFailureException.java
  src/main/java/site/youtogether/playlist/Playlist.java
  src/main/java/site/youtogether/playlist/Video.java
  src/main/java/site/youtogether/playlist/application/PlaylistService.java
  src/main/java/site/youtogether/playlist/dto/NextVideo.java
  src/main/java/site/youtogether/playlist/dto/VideoInfo.java
  src/main/java/site/youtogether/playlist/presentation/PlaylistController.java
  src/main/java/site/youtogether/room/Participant.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/presentation/RoomController.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/util/RandomUtil.java
  src/main/java/site/youtogether/util/aop/ConcurrencyHandlingAspect.java
  src/main/java/site/youtogether/util/aop/PlaylistSynchronize.java
  src/main/java/site/youtogether/util/aop/RoomSynchronize.java
  src/main/java/site/youtogether/util/aop/UserSynchronize.java
  src/test/java/site/youtogether/playlist/PlaylistTest.java
  src/test/java/site/youtogether/playlist/application/PlaylistServiceTest.java
  src/test/java/site/youtogether/playlist/presentation/PlaylistControllerTest.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
  src/test/java/site/youtogether/util/aop/ConcurrencyHandlingAspectTest.java
Labels: release

#84 feat: 유저 히스토리 길이 제한
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/user/UserTest.java
Labels: new feature

#85 release
  src/main/java/site/youtogether/message/ChatHistory.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/user/User.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/test/java/site/youtogether/room/application/RoomServiceTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/UserTest.java
Labels: release

#88 feat: 현재 재생중인 영상에 대한 정보 제공
  src/main/java/site/youtogether/message/MessageType.java
  src/main/java/site/youtogether/message/StartVideoInfoMessage.java
  src/main/java/site/youtogether/message/application/MessageService.java
  src/main/java/site/youtogether/playlist/PlayingVideo.java
  src/main/java/site/youtogether/playlist/Playlist.java
  src/main/java/site/youtogether/playlist/Video.java
  src/main/java/site/youtogether/playlist/application/PlaylistService.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/dto/RoomDetail.java
  src/main/java/site/youtogether/room/dto/RoomList.java
  src/main/java/site/youtogether/room/dto/RoomListDetail.java
  src/test/java/site/youtogether/playlist/PlaylistTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
Labels: new feature

#89 refactor: 유저가 애플리케이션 내에서 고유한 닉네임을 갖도록 구조 변경
  src/docs/asciidoc/api/user.adoc
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/user/UserNicknameDuplicateException.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/user/infrastructure/UniqueNicknameStorage.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/main/java/site/youtogether/util/DataCleaner.java
  src/main/java/site/youtogether/util/RandomUtil.java
  src/main/java/site/youtogether/util/interceptor/SessionCreateInterceptor.java
  src/main/resources/script/batch-removal-operation.lua
  src/main/resources/script/update-unique-nickname.lua
  src/test/java/site/youtogether/RestDocsSupport.java
  src/test/java/site/youtogether/user/application/UserServiceTest.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
  src/test/java/site/youtogether/util/DataCleanerTest.java
Labels: refactor

#90 release: 현재 재생중인 동영상 정보 제공 + 닉네임 유니크하도록 구조 변경
  src/docs/asciidoc/api/user.adoc
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/exception/ErrorType.java
  src/main/java/site/youtogether/exception/user/UserNicknameDuplicateException.java
  src/main/java/site/youtogether/message/MessageType.java
  src/main/java/site/youtogether/message/StartVideoInfoMessage.java
  src/main/java/site/youtogether/message/application/MessageService.java
  src/main/java/site/youtogether/playlist/PlayingVideo.java
  src/main/java/site/youtogether/playlist/Playlist.java
  src/main/java/site/youtogether/playlist/Video.java
  src/main/java/site/youtogether/playlist/application/PlaylistService.java
  src/main/java/site/youtogether/room/application/RoomService.java
  src/main/java/site/youtogether/room/dto/RoomDetail.java
  src/main/java/site/youtogether/room/dto/RoomList.java
  src/main/java/site/youtogether/room/dto/RoomListDetail.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/user/infrastructure/UniqueNicknameStorage.java
  src/main/java/site/youtogether/util/AppConstants.java
  src/main/java/site/youtogether/util/DataCleaner.java
  src/main/java/site/youtogether/util/RandomUtil.java
  src/main/java/site/youtogether/util/interceptor/SessionCreateInterceptor.java
  src/main/resources/script/batch-removal-operation.lua
  src/main/resources/script/update-unique-nickname.lua
  src/test/java/site/youtogether/RestDocsSupport.java
  src/test/java/site/youtogether/playlist/PlaylistTest.java
  src/test/java/site/youtogether/room/presentation/RoomControllerTest.java
  src/test/java/site/youtogether/user/application/UserServiceTest.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
  src/test/java/site/youtogether/util/DataCleanerTest.java
Labels: release

#91 release: 닉네임 중복 검사 API 배포
  src/docs/asciidoc/api/user.adoc
  src/main/java/site/youtogether/playlist/PlayerState.java
  src/main/java/site/youtogether/playlist/PlayingVideo.java
  src/main/java/site/youtogether/playlist/application/PlayingVideoService.java
  src/main/java/site/youtogether/playlist/infrastructure/PlayingVideoStorage.java
  src/main/java/site/youtogether/user/application/UserService.java
  src/main/java/site/youtogether/user/presentation/UserController.java
  src/main/java/site/youtogether/util/api/ResponseResult.java
  src/test/java/site/youtogether/user/presentation/UserControllerTest.java
Labels: release, documentation, new feature

#93 feat: 라이브 영상 저장 기능 구현
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/playlist/PlayingDefaultVideo.java
  src/main/java/site/youtogether/playlist/PlayingLiveVideo.java
  src/main/java/site/youtogether/playlist/PlayingVideo.java
  src/main/java/site/youtogether/playlist/Video.java
  src/main/java/site/youtogether/playlist/application/PlaylistService.java
  src/main/java/site/youtogether/playlist/infrastructure/PlayingVideoStorage.java
  src/main/java/site/youtogether/util/DataCleaner.java
  src/main/resources/script/batch-removal-operation.lua
  src/test/java/site/youtogether/util/DataCleanerTest.java
  src/test/java/site/youtogether/util/aop/ConcurrencyHandlingAspectTest.java
Labels: new feature

#94 feat: 라이브 영상 재생 기능 구현
  src/main/java/site/youtogether/config/RedisConfig.java
  src/main/java/site/youtogether/playlist/PlayingDefaultVideo.java
  src/main/java/site/youtogether/playlist/PlayingLiveVideo.java
  src/main/java/site/youtogether/playlist/PlayingVideo.java
  src/main/java/site/youtogether/playlist/Video.java
  src/main/java/site/youtogether/playlist/application/PlaylistService.java
  src/main/java/site/youtogether/playlist/infrastructure/PlayingVideoStorage.java
  src/main/java/site/youtogether/util/DataCleaner.java
  src/main/resources/script/batch-removal-operation.lua
  src/test/java/site/youtogether/util/DataCleanerTest.java
  src/test/java/site/youtogether/util/aop/ConcurrencyHandlingAspectTest.java
Labels: release
